### ISSUE TITLE
Windows 8 Support

### ISSUE THREAD

**Issue by davidgatti** [bpfliegel/Portfish#2]
Hi,

would it be possible to add support to the new threading system that Microsoft changed in the upcoming Windows 8?

**Comment by bpfliegel** [comment]
Hey David, could you please clarify what is your exact need? Sends some ref, links...

Unfortunately I did not follow Stockfish changes for quite a period and Marco did an awful lot of housekeeping - which I'm not bored enough to follow...

**Comment by davidgatti** [comment]
Basically Microsoft rewritten the thread system and changed all the methods name and some functionality. So i'm asking if you could update your code to reflect this changes.

We use your code for our game iChess3D (http://itunes.apple.com/us/app/ichess-3d/id520208375) and now we would like to port it to Windows8 but it turned out that MS changed so much that we have a big problem porting everything.

Could you give a contact to Marco - so i could ask him this?

**Comment by bpfliegel** [comment]
I think it is basically Marco to be spoken to - as I see you don't need a .Net code (which is a inferior to the original).

Stockfish is also on github, you can contact Marco there: https://github.com/mcostalba/Stockfish

Cheers, Balint

**Comment by bpfliegel** [comment]
Btw, you use the .Net port in a Mac app, did I get it correct? :)

**Comment by davidgatti** [comment]
Yes, it is correct :) why are you asking?

**Comment by bpfliegel** [comment]
Sounds strange :) Never dreamed that someone would utilize my port on a Mac if there is a C version that is an available option.... 
Anyway, Polak, Węgier, dwa bratanki, i do szabli, i do szklanki!

**Comment by davidgatti** [comment]
:)

that is because we use Unity3D to create our apps ant you writ in C# :)

**Comment by bpfliegel** [comment]
Ah, ok. Good luck with your dev!

**Comment by bpfliegel** [comment]
What is anyway strange that this is .Net code - whatever was changed on the base APIs, we are one level above, so this piece of .Net code should work fine, no? Did you do any tests? Of course, it is different for the original C version. Could you pass some info, I'm quite interested in this.

**Comment by davidgatti** [comment]
Sorry for the delay.

This is the problem that we have: http://social.msdn.microsoft.com/Forums/en-US/winappswithcsharp/thread/d71c7403-267e-41ff-9cba-4d00211f63a1 under Windows 8 RT.

**Comment by bpfliegel** [comment]
I might have some time to check on the weekend. Do you need it much or will use Stockfish and managed to speak to Marco? (just to know how urgent it is)

**Comment by davidgatti** [comment]
We would like to use your version. 

Normally we would fork your project and help you out. But sadly we are on a dead line (long story) and can't afford to do it ourself. We decided that if we can't have the AI working for the release date we won't add it for 1.0 of iChess 3D for W8RT.

If it is not to much work for you, we would be much obliged :)

**Comment by bpfliegel** [comment]
Ok, try to do my best then :)

**Comment by davidgatti** [comment]
Cool ^_^

**Comment by bpfliegel** [comment]
Oh, man, do I need to install bloody Win8 to get even close to compile it...

What is the exact problem when you compile for Win RT?
These lines only, right:
System.Threading.Thread.CurrentThread.ManagedThreadId

Could you spend a specific error/warning list? I already have an idea, just too busy to install for a day for dev env.

Cheers, Balint

**Comment by davidgatti** [comment]
I will let you know on monday because i don't have any contact with the developer during the weekend.

**Comment by bpfliegel** [comment]
Never mind, already installed a Win8 dev environment.

**Comment by bpfliegel** [comment]
Okay, see all the problems, I will let you know the results.

**Comment by bpfliegel** [comment]
Hey David,

I updated the source to compile and run under Windows RT and also created a test application to show you how it should be integrated into your application (just check the PortfishRT.sln solution) and also to test if it is okay. You can try the test app to send direct UCI commands (like 'go depth 20').

Three things remain:
1) When compiling the engine, don't forget to include the compilation directives: NETFX_CORE,PORTABLE,WINDOWS_RT (and the ones mentioned in the readme, if needed).
2) Please test and let me know your results.
3) Send the private jet with the girls.

Good luck!
Cheers, Balint

**Comment by bpfliegel** [comment]
Just to add as final note: The problem was not with Windows 8, but with Windows RT - that confused me first when you contacted me.

**Comment by davidgatti** [comment]
O wow man you are awesome! :) we will test the new version on monday. Next time you will be in Poznań, Poland let me know @dawidgatti and a will bring the girls and good beer :D

**Comment by bpfliegel** [comment]
I will do that for certain :) Please let me know the test results and good luck with your developments!
Balint

**Comment by bpfliegel** [comment]
The current version currently does not support book handling for Windows RT. Please let me know if you need this feature!

**Comment by bpfliegel** [comment]
Added book support, but had to package the original Stockfish book into the DLL (no dynamic assembly loading). Good as a first solution. Just wipe from the book.bin from the project if your app grows too large and it is not needed for you. Also, don't forget to set the OwnBook UCI option in order in case you want to use it.

Looking forward to hear your results,
Balint

**Comment by davidgatti** [comment]
Will do :)

**Comment by bpfliegel** [comment]
Hey man, no girls, no testing results, all fine?
Cheers, Balint

**Comment by bpfliegel** [comment]
No beer!

**Comment by davidgatti** [comment]
Aaa sorry man!!! everyman is ok. THX!!! for everything!!!

**Comment by bpfliegel** [comment]
Cool, good luck!
I'll close the issue.

Cheers, Balint
