### ISSUE TITLE
PortFish restart in VS2010 problem

### ISSUE THREAD

**Issue by nicelemur** [bpfliegel/Portfish#3]
Hi!
I'm a  friend of David Gatti. We successfully use your port in our Unity3d project, but I'm now developing application for Windows and encountered strange problem.
Everything is ok when I start AI for the first time in my application. 
But When I want to start it one more time (after going back to main menu of my game) it ends up with Debug assert window from method exit in class Thread. Of course I try to  ignore it but then AI is not working anyway.

So my question is: how to and end AI Thread properly so that I can start it any moment once again. Right now I send command "quit".
I wolud really appreciate your help.

**Comment by bpfliegel** [comment]
Keep one reference to it, and send 'quit' on application termination. Or send the command 'quit' to terminate it, but the better approach is to have only one ref.

**Comment by bpfliegel** [comment]
There could be only one instance at a time. As I wrote earlier, sending 'quit' terminates that instance. This is by design.

**Comment by nicelemur** [comment]
Thanks a lot. I did as you said, though I was worried about performance (my application has modes which doesn't need AI) ). Turned out everything works fine. Sorry for bothering you, I'm still learning.

**Comment by bpfliegel** [comment]
No problem really. You can send a UCI 'stop' to stop all thinking, for instance if you started an analyze mode ('go infinite'). That will still leave a couple of background threads, but they won't do any load on the CPU.
Good luck and thanks!
